-- 004_create_laporan_tambahan.sql

-- Laporan Pupuk
CREATE TABLE IF NOT EXISTS `laporan_pupuk` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `nomor_laporan` VARCHAR(20) NULL DEFAULT NULL,
    `user_id` INT UNSIGNED NOT NULL,
    `tanggal` DATE NULL DEFAULT NULL,
    `kabupaten_id` INT UNSIGNED NULL DEFAULT NULL,
    `kecamatan_id` INT UNSIGNED NULL DEFAULT NULL,
    `desa_id` INT UNSIGNED NULL DEFAULT NULL,
    `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `jenis_pupuk` ENUM('Urea','NPK','Organik','Kompos','Lainnya') NULL DEFAULT NULL,
    `dosis_per_ha` DECIMAL(8,2) NULL DEFAULT NULL,
    `luas_pemupukan` DECIMAL(8,2) NULL DEFAULT NULL,
    `metode_aplikasi` ENUM('Tabur','Kocor','Semprot','Injeksi') NULL DEFAULT NULL,
    `foto_url` VARCHAR(300) NULL DEFAULT NULL,
    `catatan` TEXT NULL DEFAULT NULL,
    `status` ENUM('Draf','Submitted','Diverifikasi','Ditolak','Diarsipkan') NOT NULL DEFAULT 'Draf',
    `verified_by` INT UNSIGNED NULL DEFAULT NULL,
    `verified_at` TIMESTAMP NULL DEFAULT NULL,
    `catatan_verifikasi` TEXT NULL DEFAULT NULL,
    `ip_pengirim` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_nomor_laporan` (`nomor_laporan`),
    KEY `idx_user` (`user_id`),
    KEY `idx_status` (`status`),
    KEY `idx_tanggal` (`tanggal`),
    KEY `idx_kecamatan` (`kecamatan_id`),
    KEY `idx_status_tanggal` (`status`, `tanggal`),
    CONSTRAINT `fk_lpupuk_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lpupuk_kabupaten` FOREIGN KEY (`kabupaten_id`) REFERENCES `master_kabupaten` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lpupuk_kecamatan` FOREIGN KEY (`kecamatan_id`) REFERENCES `master_kecamatan` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lpupuk_desa` FOREIGN KEY (`desa_id`) REFERENCES `master_desa` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lpupuk_verified_by` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT `ck_lpupuk_latitude` CHECK (`latitude` IS NULL OR (`latitude` >= -90 AND `latitude` <= 90)),
    CONSTRAINT `ck_lpupuk_longitude` CHECK (`longitude` IS NULL OR (`longitude` >= -180 AND `longitude` <= 180)),
    CONSTRAINT `ck_lpupuk_dosis` CHECK (`dosis_per_ha` IS NULL OR (`dosis_per_ha` >= 0 AND `dosis_per_ha` <= 999999.99)),
    CONSTRAINT `ck_lpupuk_luas` CHECK (`luas_pemupukan` IS NULL OR (`luas_pemupukan` >= 0 AND `luas_pemupukan` <= 999999.99))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Laporan Panen
CREATE TABLE IF NOT EXISTS `laporan_panen` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `nomor_laporan` VARCHAR(20) NULL DEFAULT NULL,
    `user_id` INT UNSIGNED NOT NULL,
    `tanggal` DATE NULL DEFAULT NULL,
    `kabupaten_id` INT UNSIGNED NULL DEFAULT NULL,
    `kecamatan_id` INT UNSIGNED NULL DEFAULT NULL,
    `desa_id` INT UNSIGNED NULL DEFAULT NULL,
    `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `komoditas` VARCHAR(100) NULL DEFAULT NULL,
    `varietas` VARCHAR(100) NULL DEFAULT NULL,
    `luas_panen` DECIMAL(8,2) NULL DEFAULT NULL,
    `hasil_panen` DECIMAL(10,2) NULL DEFAULT NULL,
    `produktivitas` DECIMAL(8,2) NULL DEFAULT NULL,
    `musim_tanam` ENUM('MT1','MT2','MT3') NULL DEFAULT NULL,
    `foto_url` VARCHAR(300) NULL DEFAULT NULL,
    `catatan` TEXT NULL DEFAULT NULL,
    `status` ENUM('Draf','Submitted','Diverifikasi','Ditolak','Diarsipkan') NOT NULL DEFAULT 'Draf',
    `verified_by` INT UNSIGNED NULL DEFAULT NULL,
    `verified_at` TIMESTAMP NULL DEFAULT NULL,
    `catatan_verifikasi` TEXT NULL DEFAULT NULL,
    `ip_pengirim` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_nomor_laporan` (`nomor_laporan`),
    KEY `idx_user` (`user_id`),
    KEY `idx_status` (`status`),
    KEY `idx_tanggal` (`tanggal`),
    KEY `idx_kecamatan` (`kecamatan_id`),
    KEY `idx_status_tanggal` (`status`, `tanggal`),
    CONSTRAINT `fk_lpanen_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lpanen_kabupaten` FOREIGN KEY (`kabupaten_id`) REFERENCES `master_kabupaten` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lpanen_kecamatan` FOREIGN KEY (`kecamatan_id`) REFERENCES `master_kecamatan` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lpanen_desa` FOREIGN KEY (`desa_id`) REFERENCES `master_desa` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lpanen_verified_by` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT `ck_lpanen_latitude` CHECK (`latitude` IS NULL OR (`latitude` >= -90 AND `latitude` <= 90)),
    CONSTRAINT `ck_lpanen_longitude` CHECK (`longitude` IS NULL OR (`longitude` >= -180 AND `longitude` <= 180)),
    CONSTRAINT `ck_lpanen_luas` CHECK (`luas_panen` IS NULL OR (`luas_panen` >= 0 AND `luas_panen` <= 999999.99)),
    CONSTRAINT `ck_lpanen_hasil` CHECK (`hasil_panen` IS NULL OR (`hasil_panen` >= 0 AND `hasil_panen` <= 99999999.99)),
    CONSTRAINT `ck_lpanen_prod` CHECK (`produktivitas` IS NULL OR (`produktivitas` >= 0 AND `produktivitas` <= 999999.99))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Laporan Cuaca
CREATE TABLE IF NOT EXISTS `laporan_cuaca` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `nomor_laporan` VARCHAR(20) NULL DEFAULT NULL,
    `user_id` INT UNSIGNED NOT NULL,
    `tanggal` DATE NULL DEFAULT NULL,
    `kabupaten_id` INT UNSIGNED NULL DEFAULT NULL,
    `kecamatan_id` INT UNSIGNED NULL DEFAULT NULL,
    `desa_id` INT UNSIGNED NULL DEFAULT NULL,
    `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `suhu_min` DECIMAL(5,2) NULL DEFAULT NULL,
    `suhu_max` DECIMAL(5,2) NULL DEFAULT NULL,
    `curah_hujan` DECIMAL(8,2) NULL DEFAULT NULL,
    `kelembaban` DECIMAL(5,2) NULL DEFAULT NULL,
    `kecepatan_angin` DECIMAL(6,2) NULL DEFAULT NULL,
    `kondisi_cuaca` ENUM('Cerah','Berawan','Hujan Ringan','Hujan Lebat','Badai') NULL DEFAULT NULL,
    `foto_url` VARCHAR(300) NULL DEFAULT NULL,
    `catatan` TEXT NULL DEFAULT NULL,
    `status` ENUM('Draf','Submitted','Diverifikasi','Ditolak','Diarsipkan') NOT NULL DEFAULT 'Draf',
    `verified_by` INT UNSIGNED NULL DEFAULT NULL,
    `verified_at` TIMESTAMP NULL DEFAULT NULL,
    `catatan_verifikasi` TEXT NULL DEFAULT NULL,
    `ip_pengirim` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_nomor_laporan` (`nomor_laporan`),
    KEY `idx_user` (`user_id`),
    KEY `idx_status` (`status`),
    KEY `idx_tanggal` (`tanggal`),
    KEY `idx_kecamatan` (`kecamatan_id`),
    KEY `idx_status_tanggal` (`status`, `tanggal`),
    CONSTRAINT `fk_lcuaca_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lcuaca_kabupaten` FOREIGN KEY (`kabupaten_id`) REFERENCES `master_kabupaten` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lcuaca_kecamatan` FOREIGN KEY (`kecamatan_id`) REFERENCES `master_kecamatan` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lcuaca_desa` FOREIGN KEY (`desa_id`) REFERENCES `master_desa` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lcuaca_verified_by` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT `ck_lcuaca_latitude` CHECK (`latitude` IS NULL OR (`latitude` >= -90 AND `latitude` <= 90)),
    CONSTRAINT `ck_lcuaca_longitude` CHECK (`longitude` IS NULL OR (`longitude` >= -180 AND `longitude` <= 180))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Laporan Alat Sarana
CREATE TABLE IF NOT EXISTS `laporan_alat_sarana` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `nomor_laporan` VARCHAR(20) NULL DEFAULT NULL,
    `user_id` INT UNSIGNED NOT NULL,
    `tanggal` DATE NULL DEFAULT NULL,
    `kabupaten_id` INT UNSIGNED NULL DEFAULT NULL,
    `kecamatan_id` INT UNSIGNED NULL DEFAULT NULL,
    `desa_id` INT UNSIGNED NULL DEFAULT NULL,
    `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `nama_alat` VARCHAR(200) NULL DEFAULT NULL,
    `jenis_sarana` ENUM('Traktor','Pompa Air','Gudang','Jalan Usaha Tani','Lainnya') NULL DEFAULT NULL,
    `kondisi` ENUM('Baik','Rusak Ringan','Rusak Berat','Tidak Layak') NULL DEFAULT NULL,
    `kapasitas` VARCHAR(100) NULL DEFAULT NULL,
    `tahun_pengadaan` YEAR NULL DEFAULT NULL,
    `foto_url` VARCHAR(300) NULL DEFAULT NULL,
    `catatan` TEXT NULL DEFAULT NULL,
    `status` ENUM('Draf','Submitted','Diverifikasi','Ditolak','Diarsipkan') NOT NULL DEFAULT 'Draf',
    `verified_by` INT UNSIGNED NULL DEFAULT NULL,
    `verified_at` TIMESTAMP NULL DEFAULT NULL,
    `catatan_verifikasi` TEXT NULL DEFAULT NULL,
    `ip_pengirim` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_nomor_laporan` (`nomor_laporan`),
    KEY `idx_user` (`user_id`),
    KEY `idx_status` (`status`),
    KEY `idx_tanggal` (`tanggal`),
    KEY `idx_kecamatan` (`kecamatan_id`),
    KEY `idx_status_tanggal` (`status`, `tanggal`),
    CONSTRAINT `fk_lalat_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lalat_kabupaten` FOREIGN KEY (`kabupaten_id`) REFERENCES `master_kabupaten` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lalat_kecamatan` FOREIGN KEY (`kecamatan_id`) REFERENCES `master_kecamatan` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lalat_desa` FOREIGN KEY (`desa_id`) REFERENCES `master_desa` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lalat_verified_by` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT `ck_lalat_latitude` CHECK (`latitude` IS NULL OR (`latitude` >= -90 AND `latitude` <= 90)),
    CONSTRAINT `ck_lalat_longitude` CHECK (`longitude` IS NULL OR (`longitude` >= -180 AND `longitude` <= 180))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
