CREATE TABLE IF NOT EXISTS `laporan_hama` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `nomor_laporan` VARCHAR(20) NULL DEFAULT NULL,
    `user_id` INT UNSIGNED NOT NULL,
    `master_opt_id` INT UNSIGNED NULL DEFAULT NULL,
    `tanggal` DATE NULL DEFAULT NULL,
    `kabupaten_id` INT UNSIGNED NULL DEFAULT NULL,
    `kecamatan_id` INT UNSIGNED NULL DEFAULT NULL,
    `desa_id` INT UNSIGNED NULL DEFAULT NULL,
    `lokasi` VARCHAR(255) NULL DEFAULT NULL,
    `alamat_lengkap` VARCHAR(300) NULL DEFAULT NULL,
    `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `tingkat_keparahan` ENUM('Ringan','Sedang','Berat') NULL DEFAULT NULL,
    `luas_serangan` DECIMAL(8,2) NULL DEFAULT NULL,
    `populasi` DECIMAL(10,2) NULL DEFAULT NULL,
    `foto_url` VARCHAR(300) NULL DEFAULT NULL,
    `catatan` TEXT NULL DEFAULT NULL,
    `status` ENUM('Draf','Submitted','Diverifikasi','Ditolak','Diarsipkan') NOT NULL DEFAULT 'Draf',
    `verified_by` INT UNSIGNED NULL DEFAULT NULL,
    `verified_at` TIMESTAMP NULL DEFAULT NULL,
    `catatan_verifikasi` TEXT NULL DEFAULT NULL,
    `ip_pengirim` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_nomor_laporan` (`nomor_laporan`),
    KEY `idx_user` (`user_id`),
    KEY `idx_opt` (`master_opt_id`),
    KEY `idx_status` (`status`),
    KEY `idx_tanggal` (`tanggal`),
    KEY `idx_kecamatan` (`kecamatan_id`),
    KEY `idx_tingkat` (`tingkat_keparahan`),
    KEY `idx_status_tanggal` (`status`, `tanggal`),
    CONSTRAINT `fk_lh_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lh_opt` FOREIGN KEY (`master_opt_id`) REFERENCES `master_opt` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lh_kabupaten` FOREIGN KEY (`kabupaten_id`) REFERENCES `master_kabupaten` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lh_kecamatan` FOREIGN KEY (`kecamatan_id`) REFERENCES `master_kecamatan` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lh_desa` FOREIGN KEY (`desa_id`) REFERENCES `master_desa` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lh_verified_by` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT `ck_lh_luas_serangan` CHECK (`luas_serangan` IS NULL OR (`luas_serangan` >= 0 AND `luas_serangan` <= 9999.99)),
    CONSTRAINT `ck_lh_latitude` CHECK (`latitude` IS NULL OR (`latitude` >= -90 AND `latitude` <= 90)),
    CONSTRAINT `ck_lh_longitude` CHECK (`longitude` IS NULL OR (`longitude` >= -180 AND `longitude` <= 180))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
