CREATE TABLE IF NOT EXISTS `laporan_irigasi` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `nomor_laporan` VARCHAR(20) NULL DEFAULT NULL,
    `user_id` INT UNSIGNED NOT NULL,
    `tanggal` DATE NULL DEFAULT NULL,
    `kabupaten_id` INT UNSIGNED NULL DEFAULT NULL,
    `kecamatan_id` INT UNSIGNED NULL DEFAULT NULL,
    `desa_id` INT UNSIGNED NULL DEFAULT NULL,
    `nama_saluran` VARCHAR(200) NULL DEFAULT NULL,
    `daerah_irigasi` VARCHAR(200) NULL DEFAULT NULL,
    `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `kondisi_fisik` ENUM('Bagus','Sedang','Tidak Bagus','Rusak') NULL DEFAULT NULL,
    `debit_air` ENUM('Cukup','Kurang','Kering') NULL DEFAULT NULL,
    `foto_url` VARCHAR(300) NULL DEFAULT NULL,
    `catatan` TEXT NULL DEFAULT NULL,
    `status` ENUM('Draf','Submitted','Diverifikasi','Ditolak','Diarsipkan') NOT NULL DEFAULT 'Draf',
    `verified_by` INT UNSIGNED NULL DEFAULT NULL,
    `verified_at` TIMESTAMP NULL DEFAULT NULL,
    `catatan_verifikasi` TEXT NULL DEFAULT NULL,
    `ip_pengirim` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_nomor_laporan` (`nomor_laporan`),
    KEY `idx_user` (`user_id`),
    KEY `idx_status` (`status`),
    KEY `idx_tanggal` (`tanggal`),
    KEY `idx_kecamatan` (`kecamatan_id`),
    KEY `idx_kondisi` (`kondisi_fisik`),
    KEY `idx_status_tanggal` (`status`, `tanggal`),
    CONSTRAINT `fk_li_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_li_kabupaten` FOREIGN KEY (`kabupaten_id`) REFERENCES `master_kabupaten` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_li_kecamatan` FOREIGN KEY (`kecamatan_id`) REFERENCES `master_kecamatan` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_li_desa` FOREIGN KEY (`desa_id`) REFERENCES `master_desa` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_li_verified_by` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT `ck_li_latitude` CHECK (`latitude` IS NULL OR (`latitude` >= -90 AND `latitude` <= 90)),
    CONSTRAINT `ck_li_longitude` CHECK (`longitude` IS NULL OR (`longitude` >= -180 AND `longitude` <= 180))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
