-- Migration 021: Create laporan_pupuk, laporan_panen, laporan_cuaca, laporan_alat_sarana tables

CREATE TABLE IF NOT EXISTS `laporan_pupuk` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `nomor_laporan` VARCHAR(20) NULL DEFAULT NULL,
    `user_id` INT UNSIGNED NOT NULL,
    `master_opt_id` INT UNSIGNED NULL DEFAULT NULL,
    `tanggal` DATE NULL DEFAULT NULL,
    `kabupaten_id` INT UNSIGNED NULL DEFAULT NULL,
    `kecamatan_id` INT UNSIGNED NULL DEFAULT NULL,
    `desa_id` INT UNSIGNED NULL DEFAULT NULL,
    `lokasi` VARCHAR(255) NULL DEFAULT NULL,
    `alamat_lengkap` VARCHAR(300) NULL DEFAULT NULL,
    `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `jenis_pupuk` VARCHAR(100) NULL DEFAULT NULL,
    `dosis` DECIMAL(10,2) NULL DEFAULT NULL,
    `satuan_dosis` VARCHAR(50) NULL DEFAULT NULL,
    `metode_aplikasi` VARCHAR(100) NULL DEFAULT NULL,
    `foto_url` VARCHAR(300) NULL DEFAULT NULL,
    `catatan` TEXT NULL DEFAULT NULL,
    `status` ENUM('Draf','Submitted','Diverifikasi','Ditolak','Diarsipkan') NOT NULL DEFAULT 'Draf',
    `verified_by` INT UNSIGNED NULL DEFAULT NULL,
    `verified_at` TIMESTAMP NULL DEFAULT NULL,
    `catatan_verifikasi` TEXT NULL DEFAULT NULL,
    `ip_pengirim` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_lp_nomor_laporan` (`nomor_laporan`),
    KEY `idx_lp_user` (`user_id`),
    KEY `idx_lp_opt` (`master_opt_id`),
    KEY `idx_lp_status` (`status`),
    KEY `idx_lp_tanggal` (`tanggal`),
    KEY `idx_lp_kecamatan` (`kecamatan_id`),
    KEY `idx_lp_jenis_pupuk` (`jenis_pupuk`),
    KEY `idx_lp_status_tanggal` (`status`, `tanggal`),
    CONSTRAINT `fk_lp_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lp_opt` FOREIGN KEY (`master_opt_id`) REFERENCES `master_opt` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lp_kabupaten` FOREIGN KEY (`kabupaten_id`) REFERENCES `master_kabupaten` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lp_kecamatan` FOREIGN KEY (`kecamatan_id`) REFERENCES `master_kecamatan` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lp_desa` FOREIGN KEY (`desa_id`) REFERENCES `master_desa` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lp_verified_by` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT `ck_lp_latitude` CHECK (`latitude` IS NULL OR (`latitude` >= -90 AND `latitude` <= 90)),
    CONSTRAINT `ck_lp_longitude` CHECK (`longitude` IS NULL OR (`longitude` >= -180 AND `longitude` <= 180))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `laporan_panen` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `nomor_laporan` VARCHAR(20) NULL DEFAULT NULL,
    `user_id` INT UNSIGNED NOT NULL,
    `master_opt_id` INT UNSIGNED NULL DEFAULT NULL,
    `tanggal` DATE NULL DEFAULT NULL,
    `kabupaten_id` INT UNSIGNED NULL DEFAULT NULL,
    `kecamatan_id` INT UNSIGNED NULL DEFAULT NULL,
    `desa_id` INT UNSIGNED NULL DEFAULT NULL,
    `lokasi` VARCHAR(255) NULL DEFAULT NULL,
    `alamat_lengkap` VARCHAR(300) NULL DEFAULT NULL,
    `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `komoditas` VARCHAR(150) NULL DEFAULT NULL,
    `luas_panen` DECIMAL(10,2) NULL DEFAULT NULL,
    `volume_panen` DECIMAL(10,2) NULL DEFAULT NULL,
    `satuan` VARCHAR(50) NULL DEFAULT NULL,
    `harga_per_unit` DECIMAL(15,2) NULL DEFAULT NULL,
    `foto_url` VARCHAR(300) NULL DEFAULT NULL,
    `catatan` TEXT NULL DEFAULT NULL,
    `status` ENUM('Draf','Submitted','Diverifikasi','Ditolak','Diarsipkan') NOT NULL DEFAULT 'Draf',
    `verified_by` INT UNSIGNED NULL DEFAULT NULL,
    `verified_at` TIMESTAMP NULL DEFAULT NULL,
    `catatan_verifikasi` TEXT NULL DEFAULT NULL,
    `ip_pengirim` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_lpan_nomor_laporan` (`nomor_laporan`),
    KEY `idx_lpan_user` (`user_id`),
    KEY `idx_lpan_status` (`status`),
    KEY `idx_lpan_tanggal` (`tanggal`),
    KEY `idx_lpan_kecamatan` (`kecamatan_id`),
    KEY `idx_lpan_komoditas` (`komoditas`),
    KEY `idx_lpan_status_tanggal` (`status`, `tanggal`),
    CONSTRAINT `fk_lpan_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lpan_opt` FOREIGN KEY (`master_opt_id`) REFERENCES `master_opt` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lpan_kabupaten` FOREIGN KEY (`kabupaten_id`) REFERENCES `master_kabupaten` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lpan_kecamatan` FOREIGN KEY (`kecamatan_id`) REFERENCES `master_kecamatan` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lpan_desa` FOREIGN KEY (`desa_id`) REFERENCES `master_desa` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lpan_verified_by` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT `ck_lpan_latitude` CHECK (`latitude` IS NULL OR (`latitude` >= -90 AND `latitude` <= 90)),
    CONSTRAINT `ck_lpan_longitude` CHECK (`longitude` IS NULL OR (`longitude` >= -180 AND `longitude` <= 180))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `laporan_cuaca` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `nomor_laporan` VARCHAR(20) NULL DEFAULT NULL,
    `user_id` INT UNSIGNED NOT NULL,
    `tanggal` DATE NULL DEFAULT NULL,
    `kabupaten_id` INT UNSIGNED NULL DEFAULT NULL,
    `kecamatan_id` INT UNSIGNED NULL DEFAULT NULL,
    `desa_id` INT UNSIGNED NULL DEFAULT NULL,
    `lokasi` VARCHAR(255) NULL DEFAULT NULL,
    `alamat_lengkap` VARCHAR(300) NULL DEFAULT NULL,
    `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `kondisi_cuaca` VARCHAR(100) NULL DEFAULT NULL,
    `suhu` DECIMAL(5,1) NULL DEFAULT NULL,
    `kelembaban` DECIMAL(5,1) NULL DEFAULT NULL,
    `curah_hujan` DECIMAL(8,2) NULL DEFAULT NULL,
    `kecepatan_angin` DECIMAL(5,1) NULL DEFAULT NULL,
    `arah_angin` VARCHAR(50) NULL DEFAULT NULL,
    `foto_url` VARCHAR(300) NULL DEFAULT NULL,
    `catatan` TEXT NULL DEFAULT NULL,
    `status` ENUM('Draf','Submitted','Diverifikasi','Ditolak','Diarsipkan') NOT NULL DEFAULT 'Draf',
    `verified_by` INT UNSIGNED NULL DEFAULT NULL,
    `verified_at` TIMESTAMP NULL DEFAULT NULL,
    `catatan_verifikasi` TEXT NULL DEFAULT NULL,
    `ip_pengirim` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_lc_nomor_laporan` (`nomor_laporan`),
    KEY `idx_lc_user` (`user_id`),
    KEY `idx_lc_status` (`status`),
    KEY `idx_lc_tanggal` (`tanggal`),
    KEY `idx_lc_kecamatan` (`kecamatan_id`),
    KEY `idx_lc_kondisi_cuaca` (`kondisi_cuaca`),
    KEY `idx_lc_status_tanggal` (`status`, `tanggal`),
    CONSTRAINT `fk_lc_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lc_kabupaten` FOREIGN KEY (`kabupaten_id`) REFERENCES `master_kabupaten` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lc_kecamatan` FOREIGN KEY (`kecamatan_id`) REFERENCES `master_kecamatan` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lc_desa` FOREIGN KEY (`desa_id`) REFERENCES `master_desa` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_lc_verified_by` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT `ck_lc_latitude` CHECK (`latitude` IS NULL OR (`latitude` >= -90 AND `latitude` <= 90)),
    CONSTRAINT `ck_lc_longitude` CHECK (`longitude` IS NULL OR (`longitude` >= -180 AND `longitude` <= 180))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `laporan_alat_sarana` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `nomor_laporan` VARCHAR(20) NULL DEFAULT NULL,
    `user_id` INT UNSIGNED NOT NULL,
    `tanggal` DATE NULL DEFAULT NULL,
    `kabupaten_id` INT UNSIGNED NULL DEFAULT NULL,
    `kecamatan_id` INT UNSIGNED NULL DEFAULT NULL,
    `desa_id` INT UNSIGNED NULL DEFAULT NULL,
    `lokasi` VARCHAR(255) NULL DEFAULT NULL,
    `alamat_lengkap` VARCHAR(300) NULL DEFAULT NULL,
    `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
    `jenis_sarana` VARCHAR(100) NULL DEFAULT NULL,
    `nama_alat` VARCHAR(200) NULL DEFAULT NULL,
    `jumlah` INT UNSIGNED NULL DEFAULT NULL,
    `kondisi` VARCHAR(100) NULL DEFAULT NULL,
    `foto_url` VARCHAR(300) NULL DEFAULT NULL,
    `catatan` TEXT NULL DEFAULT NULL,
    `status` ENUM('Draf','Submitted','Diverifikasi','Ditolak','Diarsipkan') NOT NULL DEFAULT 'Draf',
    `verified_by` INT UNSIGNED NULL DEFAULT NULL,
    `verified_at` TIMESTAMP NULL DEFAULT NULL,
    `catatan_verifikasi` TEXT NULL DEFAULT NULL,
    `ip_pengirim` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_las_nomor_laporan` (`nomor_laporan`),
    KEY `idx_las_user` (`user_id`),
    KEY `idx_las_status` (`status`),
    KEY `idx_las_tanggal` (`tanggal`),
    KEY `idx_las_kecamatan` (`kecamatan_id`),
    KEY `idx_las_jenis_sarana` (`jenis_sarana`),
    KEY `idx_las_kondisi` (`kondisi`),
    KEY `idx_las_status_tanggal` (`status`, `tanggal`),
    CONSTRAINT `fk_las_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_las_kabupaten` FOREIGN KEY (`kabupaten_id`) REFERENCES `master_kabupaten` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_las_kecamatan` FOREIGN KEY (`kecamatan_id`) REFERENCES `master_kecamatan` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_las_desa` FOREIGN KEY (`desa_id`) REFERENCES `master_desa` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `fk_las_verified_by` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT `ck_las_latitude` CHECK (`latitude` IS NULL OR (`latitude` >= -90 AND `latitude` <= 90)),
    CONSTRAINT `ck_las_longitude` CHECK (`longitude` IS NULL OR (`longitude` >= -180 AND `longitude` <= 180))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
