<?php
require_once ROOT_PATH . '/app/views/layouts/header.php';
$items = $items ?? [];
$modules = $modules ?? [];
$stats = $stats ?? [];
$total = (int) ($total ?? 0);
$page = (int) ($page ?? 1);
$perPage = (int) ($perPage ?? 20);
$totalPages = (int) ($totalPages ?? 1);
$moduleFilter = (string) ($moduleFilter ?? '');
$search = (string) ($search ?? '');
$queryForPage = static function (int $targetPage) use ($moduleFilter, $search, $perPage): string {
    return BASE_URL . 'recycle-bin?' . http_build_query(['module' => $moduleFilter, 'search' => $search, 'per_page' => $perPage, 'page' => $targetPage]);
};
?>
<style>
.recycle-page .page-heading{display:flex;align-items:center;justify-content:space-between;gap:1rem;flex-wrap:wrap}.recycle-page .summary-card{border:0;border-radius:10px;transition:transform .2s ease,box-shadow .2s ease}.recycle-page .summary-card:hover{transform:translateY(-2px);box-shadow:0 8px 22px rgba(0,0,0,.12)}.recycle-page .summary-icon{width:46px;height:46px;display:inline-flex;align-items:center;justify-content:center;border-radius:50%;background:rgba(255,255,255,.22);font-size:1.25rem}.recycle-page .filter-panel{display:flex;flex-wrap:wrap;align-items:flex-end;gap:12px;padding:16px;margin-bottom:20px;border:1px solid #dee2e6;border-radius:8px;background:linear-gradient(135deg,#f8f9fa 0%,#e9ecef 100%);box-shadow:0 2px 4px rgba(0,0,0,.05)}.recycle-page .filter-panel .form-group{margin-bottom:0;min-width:180px}.recycle-page .filter-search{flex:1 1 260px}.recycle-page .btn-action{width:32px;height:32px;padding:6px;display:inline-flex;align-items:center;justify-content:center;border-radius:6px;border:0;transition:all .2s ease;position:relative}.recycle-page .btn-action:hover{transform:translateY(-1px);box-shadow:0 4px 8px rgba(0,0,0,.15)}.recycle-page .btn-action:focus{outline:2px solid #007bff;outline-offset:2px}.recycle-page .btn-action-success{background:#28a745;color:#fff}.recycle-page .btn-action-success:hover{background:#218838;color:#fff}.recycle-page .module-badge{display:inline-flex;align-items:center;gap:6px;white-space:nowrap;padding:.42rem .58rem;border-radius:6px;font-weight:600}.recycle-page .deleted-label{max-width:360px;white-space:normal;word-break:break-word}.recycle-page .mobile-item{display:none;border-left:4px solid #6c757d}.recycle-page .empty-state{padding:3rem 1rem;text-align:center;color:#6c757d}.recycle-page .empty-state i{font-size:3rem;margin-bottom:1rem;color:#adb5bd}.recycle-page .table thead th{white-space:nowrap;vertical-align:middle}.recycle-page .pagination-summary{color:#6c757d;font-size:.875rem}@media(max-width:767.98px){.recycle-page .desktop-table{display:none}.recycle-page .mobile-item{display:block}.recycle-page .page-heading .btn{width:100%}.recycle-page .filter-panel{flex-direction:column;align-items:stretch}.recycle-page .filter-panel .form-group,.recycle-page .filter-search{width:100%;min-width:0;flex-basis:auto}.recycle-page .filter-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.recycle-page .summary-card{margin-bottom:.75rem}}@media(min-width:768px) and (max-width:991.98px){.recycle-page .deleted-label{max-width:240px}.recycle-page .btn-action{width:34px;height:34px}}@media(prefers-reduced-motion:reduce){.recycle-page *,.recycle-page *::before,.recycle-page *::after{transition:none!important;animation:none!important}}
.recycle-page .recycle-check{width:18px;height:18px;cursor:pointer;accent-color:#28a745}.recycle-page .bulk-actions{display:flex;gap:8px;flex-wrap:wrap}
.recycle-page *,.recycle-page *::before,.recycle-page *::after{animation:none!important;transition:none!important}.recycle-page .summary-card,.recycle-page .summary-card:hover,.recycle-page .card,.recycle-page .card:hover,.recycle-page .btn,.recycle-page .btn:hover,.recycle-page .btn:focus,.recycle-page .btn:active,.recycle-page .btn-action,.recycle-page .btn-action:hover,.recycle-page .table tbody tr,.recycle-page .table tbody tr:hover,.recycle-page .page-link,.recycle-page .form-control,.recycle-page .badge,.recycle-page .alert,.recycle-page .recycle-check{transform:none!important;animation:none!important;transition:none!important}.recycle-page .summary-card:hover,.recycle-page .card:hover,.recycle-page .btn:hover,.recycle-page .btn:focus,.recycle-page .btn:active,.recycle-page .btn-action:hover,.recycle-page .table tbody tr:hover{box-shadow:none!important}.modal#restoreModal,.modal#restoreModal .modal-dialog,.modal-backdrop{animation:none!important;transition:none!important;transform:none!important}
</style>
<div class="container-fluid recycle-page">
 <div class="page-heading row mb-3"><div class="col-md-7"><h1><i class="fas fa-recycle text-primary"></i> Recycle Bin</h1><p class="text-muted mb-0">Kelola dan pulihkan data pelaporan yang telah dihapus.</p></div><div class="col-md-5 text-md-right mt-2 mt-md-0"><a href="<?= BASE_URL ?>dashboard" class="btn btn-primary"><i class="fas fa-arrow-left"></i> Kembali ke Dashboard</a></div></div>
 <div class="row">
 <?php $cardStyles=['usulan-opt'=>'bg-success','laporan'=>'bg-danger','irigasi'=>'bg-primary','laporan-lainnya'=>'bg-info']; foreach($modules as $key=>$definition): ?>
  <div class="col-6 col-lg-3"><a href="<?= BASE_URL ?>recycle-bin?module=<?= urlencode((string)$key) ?>" class="text-decoration-none"><div class="card summary-card <?= $cardStyles[$key]??'bg-secondary' ?> text-white"><div class="card-body d-flex align-items-center justify-content-between py-3"><div><div class="h4 mb-0"><?= (int)($stats[$key]??0) ?></div><small><?= htmlspecialchars((string)$definition['name']) ?></small></div><span class="summary-icon"><i class="fas <?= htmlspecialchars((string)$definition['icon']) ?>"></i></span></div></div></a></div>
 <?php endforeach; ?>
 </div>
 <div class="card shadow"><div class="card-body">
  <form method="GET" action="<?= BASE_URL ?>recycle-bin" class="filter-panel" id="recycleFilterForm">
   <div class="form-group"><label for="moduleFilter">Modul</label><select class="form-control" id="moduleFilter" name="module"><option value="">Semua Modul</option><?php foreach($modules as $key=>$definition): ?><option value="<?= htmlspecialchars((string)$key) ?>" <?= $moduleFilter===$key?'selected':'' ?>><?= htmlspecialchars((string)$definition['name']) ?></option><?php endforeach; ?></select></div>
   <div class="form-group filter-search"><label for="recycleSearch">Cari data</label><input type="search" class="form-control" id="recycleSearch" name="search" maxlength="100" value="<?= htmlspecialchars($search) ?>" placeholder="Cari nomor atau nama data..."></div>
   <div class="form-group"><label for="perPage">Baris</label><select class="form-control" id="perPage" name="per_page"><?php foreach([10,20,50,100] as $size): ?><option value="<?= $size ?>" <?= $perPage===$size?'selected':'' ?>><?= $size ?></option><?php endforeach; ?></select></div>
   <div class="filter-actions"><button type="submit" class="btn btn-primary"><i class="fas fa-search"></i> Terapkan</button> <a href="<?= BASE_URL ?>recycle-bin" class="btn btn-outline-secondary"><i class="fas fa-undo"></i> Reset</a></div>
  </form>
  <div class="d-flex justify-content-between align-items-center flex-wrap mb-3"><div><strong><?= number_format($total,0,',','.') ?></strong> data ditemukan</div><span class="pagination-summary">Halaman <?= $page ?> dari <?= $totalPages ?></span></div>
  <?php if($items!==[]): ?><div class="bulk-actions mb-3"><button type="button" class="btn btn-outline-success btn-sm" id="recycleSelectAllData"><i class="fas fa-check-double"></i> Pilih Semua Halaman Ini</button><button type="button" class="btn btn-success btn-sm" id="recycleRestoreSelected" disabled><i class="fas fa-undo"></i> Pulihkan Terpilih (<span id="recycleSelectedCount">0</span>)</button><button type="button" class="btn btn-outline-success btn-sm" id="recycleRestoreAll"><i class="fas fa-undo-alt"></i> Pulihkan Semua<?= $moduleFilter!==''?' Modul Ini':'' ?></button><button type="button" class="btn btn-danger btn-sm" id="recycleDeleteSelected" disabled><i class="fas fa-trash-alt"></i> Hapus Terpilih (<span id="recycleDeleteSelectedCount">0</span>)</button><button type="button" class="btn btn-outline-danger btn-sm" id="recycleDeleteAll"><i class="fas fa-trash"></i> Hapus Semua<?= $moduleFilter!==''?' Modul Ini':'' ?></button></div><?php endif; ?>
  <?php if($items===[]): ?><div class="empty-state" role="status"><i class="fas fa-recycle" aria-hidden="true"></i><h4>Recycle bin kosong</h4><p class="mb-0"><?= ($moduleFilter!==''||$search!=='')?'Tidak ada data yang sesuai dengan filter.':'Belum ada data yang dipindahkan ke recycle bin.' ?></p></div>
  <?php else: ?>
  <div class="table-responsive desktop-table"><table class="table table-bordered table-hover" id="recycleTable"><thead class="thead-light"><tr><th width="40" class="text-center"><input type="checkbox" class="recycle-check" id="recycleSelectAll" aria-label="Pilih semua data halaman ini"></th><th width="55" class="text-center">No</th><th>Modul</th><th>Data</th><th>Dihapus pada</th><th>Dihapus oleh</th><th width="90" class="text-center">Aksi</th></tr></thead><tbody>
  <?php foreach($items as $index=>$item): ?><tr><td class="text-center"><input type="checkbox" class="recycle-check recycle-item-check" value="<?= htmlspecialchars((string)$item['module'].':'.(int)$item['id']) ?>"></td><td class="text-center text-muted"><?= (($page-1)*$perPage)+$index+1 ?></td><td><span class="badge badge-secondary module-badge"><i class="fas <?= htmlspecialchars((string)$item['module_icon']) ?>"></i><?= htmlspecialchars((string)$item['module_name']) ?></span></td><td class="deleted-label"><strong><?= htmlspecialchars((string)($item['label']?:'ID #'.$item['id'])) ?></strong><br><small class="text-muted">ID #<?= (int)$item['id'] ?></small></td><td><i class="far fa-clock text-muted mr-1"></i><?= htmlspecialchars(date('d/m/Y H:i',strtotime((string)$item['deleted_at']))) ?></td><td><?= htmlspecialchars((string)($item['deleted_by_name']??'-')) ?></td><td class="text-center"><button type="button" class="btn-action btn-action-success js-restore" title="Pulihkan data" aria-label="Pulihkan data" data-module="<?= htmlspecialchars((string)$item['module']) ?>" data-id="<?= (int)$item['id'] ?>" data-label="<?= htmlspecialchars((string)($item['label']?:'ID #'.$item['id']),ENT_QUOTES,'UTF-8') ?>"><i class="fas fa-undo"></i></button></td></tr><?php endforeach; ?>
  </tbody></table></div>
  <div class="mobile-list"><?php foreach($items as $item): ?><div class="card mobile-item mb-3 shadow-sm"><div class="card-body"><div class="d-flex justify-content-between align-items-start mb-2"><div><input type="checkbox" class="recycle-check recycle-item-check mr-2" value="<?= htmlspecialchars((string)$item['module'].':'.(int)$item['id']) ?>" aria-label="Pilih data ini"><span class="badge badge-secondary module-badge"><i class="fas <?= htmlspecialchars((string)$item['module_icon']) ?>"></i><?= htmlspecialchars((string)$item['module_name']) ?></span></div><button type="button" class="btn-action btn-action-success js-restore" title="Pulihkan data" aria-label="Pulihkan data" data-module="<?= htmlspecialchars((string)$item['module']) ?>" data-id="<?= (int)$item['id'] ?>" data-label="<?= htmlspecialchars((string)($item['label']?:'ID #'.$item['id']),ENT_QUOTES,'UTF-8') ?>"><i class="fas fa-undo"></i></button></div><h5 class="mb-1"><?= htmlspecialchars((string)($item['label']?:'ID #'.$item['id'])) ?></h5><small class="text-muted d-block mb-2">ID #<?= (int)$item['id'] ?></small><div class="small"><i class="far fa-clock mr-1"></i><?= htmlspecialchars(date('d/m/Y H:i',strtotime((string)$item['deleted_at']))) ?></div><div class="small"><i class="far fa-user mr-1"></i><?= htmlspecialchars((string)($item['deleted_by_name']??'-')) ?></div></div></div><?php endforeach; ?></div>
  <?php endif; ?>
  <?php if($totalPages>1): ?><div class="d-flex justify-content-between align-items-center flex-wrap mt-3"><span class="pagination-summary">Menampilkan <?= (($page-1)*$perPage)+1 ?>–<?= min($page*$perPage,$total) ?> dari <?= $total ?></span><nav aria-label="Navigasi recycle bin"><ul class="pagination pagination-sm mb-0"><li class="page-item <?= $page<=1?'disabled':'' ?>"><a class="page-link" href="<?= $page>1?htmlspecialchars($queryForPage($page-1)):'#' ?>">Sebelumnya</a></li><li class="page-item disabled"><span class="page-link">Halaman <?= $page ?> / <?= $totalPages ?></span></li><li class="page-item <?= $page>=$totalPages?'disabled':'' ?>"><a class="page-link" href="<?= $page<$totalPages?htmlspecialchars($queryForPage($page+1)):'#' ?>">Berikutnya</a></li></ul></nav></div><?php endif; ?>
 </div></div>
</div>
<div class="modal fade" id="restoreModal" tabindex="-1" role="dialog" aria-labelledby="restoreModalTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered" role="document"><div class="modal-content"><div class="modal-header bg-success text-white"><h5 class="modal-title" id="restoreModalTitle"><i class="fas fa-undo"></i> Pulihkan Data</h5><button type="button" class="close text-white" data-dismiss="modal" aria-label="Tutup"><span aria-hidden="true">&times;</span></button></div><form method="POST" action="<?= BASE_URL ?>recycle-bin/restore" id="restoreForm"><div class="modal-body"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(Security::getCsrfToken(),ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="module" id="restoreModule"><input type="hidden" name="id" id="restoreId"><p class="mb-2">Pulihkan data berikut ke daftar aktif?</p><div class="alert alert-light border mb-0"><strong id="restoreLabel">-</strong></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button><button type="submit" class="btn btn-success" id="restoreSubmit"><i class="fas fa-undo"></i> Ya, Pulihkan</button></div></form></div></div></div>
<form method="POST" action="<?= BASE_URL ?>recycle-bin/bulk-restore" id="bulkRestoreForm" class="d-none"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(Security::getCsrfToken(),ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="module" value="<?= htmlspecialchars($moduleFilter,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="restore_all" id="bulkRestoreAll" value="0"><div id="bulkRestoreItems"></div></form>
<form method="POST" action="<?= BASE_URL ?>recycle-bin/bulk-delete" id="bulkDeleteForm" class="d-none"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(Security::getCsrfToken(),ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="module" value="<?= htmlspecialchars($moduleFilter,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="delete_all" id="bulkDeleteAll" value="0"><div id="bulkDeleteItems"></div></form>
<script>
(function(){
 'use strict';
 const itemChecks=Array.from(document.querySelectorAll('.recycle-item-check'));
 const master=document.getElementById('recycleSelectAll');
 const selectAllButton=document.getElementById('recycleSelectAllData');
 const selectedButton=document.getElementById('recycleRestoreSelected');
 const allButton=document.getElementById('recycleRestoreAll');
 const selectedCount=document.getElementById('recycleSelectedCount');
 const deleteSelectedButton=document.getElementById('recycleDeleteSelected');
 const deleteAllButton=document.getElementById('recycleDeleteAll');
 const deleteSelectedCount=document.getElementById('recycleDeleteSelectedCount');
 const bulkForm=document.getElementById('bulkRestoreForm');
 const bulkDeleteForm=document.getElementById('bulkDeleteForm');
 const filterForm=document.getElementById('recycleFilterForm');
 const perPageSelect=document.getElementById('perPage');
 const uniqueValues=()=>Array.from(new Set(itemChecks.filter(box=>box.checked).map(box=>box.value)));
 function sync(value,checked){itemChecks.filter(box=>box.value===value).forEach(box=>{box.checked=checked})}
 function update(){const selected=uniqueValues();if(selectedCount)selectedCount.textContent=selected.length;if(deleteSelectedCount)deleteSelectedCount.textContent=selected.length;if(selectedButton)selectedButton.disabled=selected.length===0;if(deleteSelectedButton)deleteSelectedButton.disabled=selected.length===0;if(master){const pageValues=new Set(itemChecks.map(box=>box.value));master.checked=pageValues.size>0&&selected.length===pageValues.size;master.indeterminate=selected.length>0&&selected.length<pageValues.size}if(selectAllButton)selectAllButton.innerHTML=master&&master.checked?'<i class="fas fa-times"></i> Batalkan Semua Pilihan':'<i class="fas fa-check-double"></i> Pilih Semua Halaman Ini'}
 itemChecks.forEach(box=>box.addEventListener('change',function(){sync(this.value,this.checked);update()}));
 if(master)master.addEventListener('change',function(){itemChecks.forEach(box=>{box.checked=this.checked});update()});
 if(selectAllButton)selectAllButton.addEventListener('click',function(){const choose=!(master&&master.checked);itemChecks.forEach(box=>{box.checked=choose});update()});
 if(selectedButton)selectedButton.addEventListener('click',function(){const values=uniqueValues();if(!values.length||!confirm(`Pulihkan ${values.length} data terpilih?`))return;document.getElementById('bulkRestoreAll').value='0';const holder=document.getElementById('bulkRestoreItems');holder.replaceChildren();values.forEach(value=>{const input=document.createElement('input');input.type='hidden';input.name='items[]';input.value=value;holder.appendChild(input)});bulkForm.submit()});
 if(allButton)allButton.addEventListener('click',function(){if(!confirm('Pulihkan semua data<?= $moduleFilter!==''?' pada modul ini':' dari seluruh modul' ?>?'))return;document.getElementById('bulkRestoreAll').value='1';document.getElementById('bulkRestoreItems').replaceChildren();bulkForm.submit()});
 if(deleteSelectedButton)deleteSelectedButton.addEventListener('click',function(){const values=uniqueValues();if(!values.length||!confirm(`Hapus permanen ${values.length} data terpilih? Data tidak dapat dipulihkan kembali.`))return;document.getElementById('bulkDeleteAll').value='0';const holder=document.getElementById('bulkDeleteItems');holder.replaceChildren();values.forEach(value=>{const input=document.createElement('input');input.type='hidden';input.name='items[]';input.value=value;holder.appendChild(input)});deleteSelectedButton.disabled=true;bulkDeleteForm.submit()});
 if(deleteAllButton)deleteAllButton.addEventListener('click',function(){if(!confirm('Hapus permanen semua data<?= $moduleFilter!==''?' pada modul ini':' dari seluruh modul' ?>? Data tidak dapat dipulihkan kembali.'))return;document.getElementById('bulkDeleteAll').value='1';document.getElementById('bulkDeleteItems').replaceChildren();deleteAllButton.disabled=true;bulkDeleteForm.submit()});
 document.querySelectorAll('.js-restore').forEach(function(button){button.addEventListener('click',function(){document.getElementById('restoreModule').value=button.dataset.module||'';document.getElementById('restoreId').value=button.dataset.id||'';document.getElementById('restoreLabel').textContent=button.dataset.label||'-';$('#restoreModal').modal('show')})});
 document.getElementById('restoreForm').addEventListener('submit',function(){const submit=document.getElementById('restoreSubmit');submit.disabled=true;submit.innerHTML='<i class="fas fa-spinner fa-spin"></i> Memulihkan...'});
 if(filterForm&&perPageSelect&&perPageSelect.dataset.autoSubmitBound!=='1'){
  perPageSelect.dataset.autoSubmitBound='1';
  perPageSelect.addEventListener('change',function(){filterForm.setAttribute('aria-busy','true');filterForm.submit()});
 }
 update();
})();
</script>
<?php require_once ROOT_PATH . '/app/views/layouts/footer.php'; ?>
